import mongoose from "mongoose";
import dotenv from "dotenv";
import Movie from "../models/Movie.js";
import User from "../models/User.js";

dotenv.config();

const movies = [
  { title: "The Witcher", description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.", poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg", genre: ["Fantasy", "Action", "Adventure"], year: 2019, director: "Lauren Schmidt Hissrich", rating: 8.1, duration: 60, trailerUrl: "https://www.youtube.com/embed/ndl1W4ltcmg" },
  { title: "Mission Impossible - Dead Reckoning", description: "With the price on his head ever increasing, legendary hit man Ethan Hunt takes his fight against the High Table global as he seeks out the most powerful players in the underworld.", poster: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg", genre: ["Action", "Thriller"], year: 2023, director: "Christopher McQuarrie", rating: 7.7, duration: 163, trailerUrl: "https://www.youtube.com/embed/avz06PDqDbM" },
  { title: "Peaky Blinders", description: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.", poster: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg", genre: ["Crime", "Drama"], year: 2013, director: "Steven Knight", rating: 8.8, duration: 55, trailerUrl: "https://www.youtube.com/embed/2wJ4nq5xkfw" },
  { title: "Inception", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.", poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", genre: ["Sci-Fi", "Thriller"], year: 2010, director: "Christopher Nolan", rating: 8.8, duration: 148, trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0" },
  { title: "Breaking Bad", description: "A chemistry teacher diagnosed with cancer teams up with a former student to secure his family's future by manufacturing and selling crystal meth.", poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", genre: ["Crime", "Drama"], year: 2008, director: "Vince Gilligan", rating: 9.5, duration: 47, trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY" },
  { title: "Stranger Things", description: "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.", poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", genre: ["Sci-Fi", "Horror", "Drama"], year: 2016, director: "The Duffer Brothers", rating: 8.7, duration: 51, trailerUrl: "https://www.youtube.com/embed/b9EkMc79ZSU" },
  { title: "The Dark Knight", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.", poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", genre: ["Action", "Crime", "Drama"], year: 2008, director: "Christopher Nolan", rating: 9.0, duration: 152, trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY" },
  { title: "Interstellar", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", genre: ["Sci-Fi", "Adventure", "Drama"], year: 2014, director: "Christopher Nolan", rating: 8.7, duration: 169, trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E" },
  { title: "Money Heist", description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.", poster: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", genre: ["Crime", "Drama", "Thriller"], year: 2017, director: "Álex Pina", rating: 8.2, duration: 70, trailerUrl: "https://www.youtube.com/embed/36wCVZDBw_o" },
  { title: "Joker", description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society, leading him on a downward spiral.", poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", genre: ["Crime", "Drama", "Thriller"], year: 2019, director: "Todd Phillips", rating: 8.4, duration: 122, trailerUrl: "https://www.youtube.com/embed/zAGVQLHvwOY" },
  { title: "Game of Thrones", description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.", poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg", genre: ["Fantasy", "Drama", "Action"], year: 2011, director: "David Benioff", rating: 9.2, duration: 57, trailerUrl: "https://www.youtube.com/embed/KPLWWIOCOOQ" },
  { title: "Godzilla Minus One", description: "Post-war Japan is at its lowest point when a new crisis emerges in the form of a giant monster.", poster: "https://image.tmdb.org/t/p/w500/pJmaMSU3f0i4ZbXvXTvHnQY99Ne.jpg", genre: ["Sci-Fi", "Horror", "Action"], year: 2023, director: "Takashi Yamazaki", rating: 7.7, duration: 125, trailerUrl: "https://www.youtube.com/embed/JD1DkkFEVpg" },
  { title: "Kung Fu Panda", description: "A lazy panda must fulfill his destiny as the Dragon Warrior after being unexpectedly chosen.", poster: "https://image.tmdb.org/t/p/w500/wa4EyvSJ3x2u10c9dfPtIt6uK7g.jpg", genre: ["Animation", "Comedy", "Adventure"], year: 2008, director: "Mark Osborne", rating: 7.6, duration: 92, trailerUrl: "https://www.youtube.com/embed/hMP2GbS_JLs" },
  { title: "Killers of the Flower Moon", description: "Members of the Osage tribe are murdered under mysterious circumstances in the 1920s, sparking a major F.B.I. investigation.", poster: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg", genre: ["Crime", "Drama", "Mystery"], year: 2023, director: "Martin Scorsese", rating: 7.6, duration: 206, trailerUrl: "https://www.youtube.com/embed/EP34Yoxs3FQ" },
  { title: "John Wick", description: "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.", poster: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg", genre: ["Action", "Thriller", "Crime"], year: 2014, director: "Chad Stahelski", rating: 7.4, duration: 101, trailerUrl: "https://www.youtube.com/embed/2AUmvWm5ZDQ" },
  { title: "La La Land", description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", genre: ["Romance", "Drama", "Comedy"], year: 2016, director: "Damien Chazelle", rating: 8.0, duration: 128, trailerUrl: "https://www.youtube.com/embed/0pdqf4P9MB8" },
  { title: "Venom", description: "A failed reporter becomes host to an alien symbiote, which gives him a variety of new abilities that turn him into the antihero Venom.", poster: "https://image.tmdb.org/t/p/w500/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg", genre: ["Action", "Sci-Fi", "Thriller"], year: 2018, director: "Ruben Fleischer", rating: 6.6, duration: 112, trailerUrl: "https://www.youtube.com/embed/u9Mv98Gr5pY" },
  { title: "Captain Marvel", description: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.", poster: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg", genre: ["Action", "Adventure", "Sci-Fi"], year: 2019, director: "Anna Boden", rating: 6.8, duration: 123, trailerUrl: "https://www.youtube.com/embed/Z1BCujX3pw8" },
  { title: "Indiana Jones and the Dial of Destiny", description: "Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.", poster: "https://image.tmdb.org/t/p/w500/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg", genre: ["Adventure", "Action"], year: 2023, director: "James Mangold", rating: 6.5, duration: 154, trailerUrl: "https://www.youtube.com/embed/eQfMbSe7F2g" },
  { title: "Avengers: Endgame", description: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.", poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", genre: ["Action", "Adventure", "Sci-Fi"], year: 2019, director: "Anthony Russo", rating: 8.4, duration: 181, trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c" },
  { title: "Coco", description: "Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer.", poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg", genre: ["Animation", "Adventure", "Drama"], year: 2017, director: "Lee Unkrich", rating: 8.4, duration: 105, trailerUrl: "https://www.youtube.com/embed/xlnPHQ3TLX8" },
  { title: "Toy Story", description: "A cowboy doll is profoundly threatened when a new spaceman action figure supplants him as top toy in a boy's bedroom.", poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", genre: ["Animation", "Adventure", "Comedy"], year: 1995, director: "John Lasseter", rating: 8.3, duration: 81, trailerUrl: "https://www.youtube.com/embed/v-PjgYDrg70" },
  { title: "Shrek", description: "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest to reclaim his land.", poster: "https://image.tmdb.org/t/p/w500/dNVtpMlR0FBOnJZTOhh4XChZuJ0.jpg", genre: ["Animation", "Comedy", "Adventure"], year: 2001, director: "Andrew Adamson", rating: 7.9, duration: 90, trailerUrl: "https://www.youtube.com/embed/CwXOrWvPBPk" },
  { title: "Frozen", description: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice, she must find a way to reverse the winter she's created.", poster: "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg", genre: ["Animation", "Adventure", "Fantasy"], year: 2013, director: "Chris Buck", rating: 7.3, duration: 102, trailerUrl: "https://www.youtube.com/embed/TbQm5doF_Uc" },
  { title: "The Conjuring", description: "Paranormal investigators help a family terrorized by a dark presence in their farmhouse.", poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg", genre: ["Horror", "Mystery", "Thriller"], year: 2013, director: "James Wan", rating: 7.5, duration: 112, trailerUrl: "https://www.youtube.com/embed/k10ETZ41q5o" },
  { title: "Get Out", description: "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness escalates into horror.", poster: "https://image.tmdb.org/t/p/w500/1SwKingaSKM9nSHFcDbAsg2LVJp.jpg", genre: ["Horror", "Mystery", "Thriller"], year: 2017, director: "Jordan Peele", rating: 7.7, duration: 104, trailerUrl: "https://www.youtube.com/embed/DzfpyUB60YY" },
  { title: "A Quiet Place", description: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.", poster: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg", genre: ["Horror", "Sci-Fi", "Thriller"], year: 2018, director: "John Krasinski", rating: 7.5, duration: 90, trailerUrl: "https://www.youtube.com/embed/WR7cc5t7tv8" },
  { title: "Hereditary", description: "A grieving family is haunted by tragedy and disturbing secrets that come to light after their matriarch's death.", poster: "https://image.tmdb.org/t/p/w500/p9fmuz2Oj3HGterCf0Zc5s5gS83.jpg", genre: ["Horror", "Mystery", "Drama"], year: 2018, director: "Ari Aster", rating: 7.3, duration: 127, trailerUrl: "https://www.youtube.com/embed/V6wWKNej_3M" },
  { title: "The Notebook", description: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.", poster: "https://image.tmdb.org/t/p/w500/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg", genre: ["Romance", "Drama"], year: 2004, director: "Nick Cassavetes", rating: 7.8, duration: 123, trailerUrl: "https://www.youtube.com/embed/tHOgVW4c9Wk" },
  { title: "Pride and Prejudice", description: "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.", poster: "https://image.tmdb.org/t/p/w500/oPtSEuTQ68iAmedvj3WHtRIVFxN.jpg", genre: ["Romance", "Drama"], year: 2005, director: "Joe Wright", rating: 7.8, duration: 129, trailerUrl: "https://www.youtube.com/embed/1dGriB3Qsic" },
  { title: "Titanic", description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", genre: ["Romance", "Drama"], year: 1997, director: "James Cameron", rating: 7.9, duration: 195, trailerUrl: "https://www.youtube.com/embed/kVrqfYjkTdQ" },
  { title: "To All the Boys I've Loved Before", description: "A teen's love letters to five boys are mailed out without her knowledge, upending her love life.", poster: "https://image.tmdb.org/t/p/w500/pDR2gtIVFvssiwjyfnQCwESVtu2.jpg", genre: ["Romance", "Comedy"], year: 2018, director: "Susan Johnson", rating: 7.5, duration: 100, trailerUrl: "https://www.youtube.com/embed/AnnV-BHDllU" },
  { title: "Knives Out", description: "A detective investigates the death of a patriarch of an eccentric, combative family.", poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg", genre: ["Mystery", "Comedy", "Crime"], year: 2019, director: "Rian Johnson", rating: 7.9, duration: 130, trailerUrl: "https://www.youtube.com/embed/qGqiHJTsRkQ" },
  { title: "Sherlock Holmes", description: "Detective Sherlock Holmes and his stalwart partner Watson engage in a battle of wits and brawn with a nemesis.", poster: "https://image.tmdb.org/t/p/w500/hjcRVLcOZq2FTx9M5WKNv8yLzka.jpg", genre: ["Mystery", "Action", "Adventure"], year: 2009, director: "Guy Ritchie", rating: 7.6, duration: 128, trailerUrl: "https://www.youtube.com/embed/UBcc_ZgFm5g" },
  { title: "Harry Potter and the Sorcerer's Stone", description: "An orphaned boy discovers he is a wizard on his 11th birthday and enrolls at a magical school.", poster: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg", genre: ["Fantasy", "Adventure"], year: 2001, director: "Chris Columbus", rating: 7.6, duration: 152, trailerUrl: "https://www.youtube.com/embed/VyHV0BRtdxo" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", description: "A meek Hobbit and his companions set out to destroy a powerful ring and save Middle-earth.", poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", genre: ["Fantasy", "Adventure", "Action"], year: 2001, director: "Peter Jackson", rating: 8.8, duration: 178, trailerUrl: "https://www.youtube.com/embed/V75dMMIW2B4" },
  { title: "The Hangover", description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the groom missing.", poster: "https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63X9VHCLWDAYP.jpg", genre: ["Comedy"], year: 2009, director: "Todd Phillips", rating: 7.7, duration: 100, trailerUrl: "https://www.youtube.com/embed/uHTj5mIGVv4" },
  { title: "Superbad", description: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.", poster: "https://image.tmdb.org/t/p/w500/uCsSbrfAgWq35DDafphYPFmn7hb.jpg", genre: ["Comedy"], year: 2007, director: "Greg Mottola", rating: 7.6, duration: 113, trailerUrl: "https://www.youtube.com/embed/L3gJKuUEmVQ" },
  { title: "Deadpool", description: "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.", poster: "https://image.tmdb.org/t/p/w500/fSRb7vyIP2rmt19j6sxppQ96afC.jpg", genre: ["Action", "Comedy", "Sci-Fi"], year: 2016, director: "Tim Miller", rating: 7.6, duration: 108, trailerUrl: "https://www.youtube.com/embed/Xithigfg7dA" },
  { title: "Guardians of the Galaxy", description: "A group of intergalactic criminals must pull together to stop a fanatical warrior from taking control of the universe.", poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg", genre: ["Action", "Adventure", "Comedy", "Sci-Fi"], year: 2014, director: "James Gunn", rating: 8.0, duration: 121, trailerUrl: "https://www.youtube.com/embed/d96cjJhvlMA" },
  { title: "Ratatouille", description: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.", poster: "https://image.tmdb.org/t/p/w500/t3vaWRPSf07VsoxFcS1QAasQCZ7.jpg", genre: ["Animation", "Comedy"], year: 2007, director: "Brad Bird", rating: 8.0, duration: 111, trailerUrl: "https://www.youtube.com/embed/c3sBBRxDAqk" },
  { title: "Moana", description: "In Ancient Polynesia, a young girl is chosen by the ocean to reunite a mystical relic with a goddess.", poster: "https://image.tmdb.org/t/p/w500/4JeejGugONWpJkbnvL12hVoYEDa.jpg", genre: ["Animation", "Adventure", "Fantasy"], year: 2016, director: "Ron Clements", rating: 7.6, duration: 107, trailerUrl: "https://www.youtube.com/embed/LKFuXETZUsI" },
  { title: "The Princess Bride", description: "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles.", poster: "https://image.tmdb.org/t/p/w500/dvjqlp2sAhUeFjUOfQDgqwpxcp3.jpg", genre: ["Fantasy", "Romance", "Adventure"], year: 1987, director: "Rob Reiner", rating: 7.9, duration: 98, trailerUrl: "https://www.youtube.com/embed/WT_lbrhbP6M" },
  { title: "Twilight", description: "A teenage girl risks everything when she falls in love with a vampire.", poster: "https://image.tmdb.org/t/p/w500/6926DfmilFEQeE5oiOOOAdPHnMV.jpg", genre: ["Romance", "Fantasy", "Drama"], year: 2008, director: "Catherine Hardwicke", rating: 5.2, duration: 122, trailerUrl: "https://www.youtube.com/embed/UZia7l9m4Ac" },
  { title: "Sixteen Candles", description: "A young woman's sixteenth birthday becomes more of a nightmare than a celebration.", poster: "https://image.tmdb.org/t/p/w500/1FdY8Rf5PBRnyfHzuLcMi3zHJvR.jpg", genre: ["Romance", "Comedy"], year: 1984, director: "John Hughes", rating: 6.9, duration: 93, trailerUrl: "https://www.youtube.com/embed/qEZlk1LtoJk" },
  { title: "Zodiac", description: "In the late 1960s and early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.", poster: "https://image.tmdb.org/t/p/w500/6YLIAyt2VVQ7fXtaWPfsx7bMLdV.jpg", genre: ["Mystery", "Crime", "Thriller"], year: 2007, director: "David Fincher", rating: 7.7, duration: 157, trailerUrl: "https://www.youtube.com/embed/yamq5MgSK7A" },
  { title: "Se7en", description: "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.", poster: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg", genre: ["Mystery", "Crime", "Thriller", "Horror"], year: 1995, director: "David Fincher", rating: 8.6, duration: 127, trailerUrl: "https://www.youtube.com/embed/znmZoVkCjpI" },
  { title: "Spirited Away", description: "During her family's move, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", genre: ["Animation", "Fantasy", "Adventure"], year: 2001, director: "Hayao Miyazaki", rating: 8.6, duration: 125, trailerUrl: "https://www.youtube.com/embed/ByXuk9QqQkk" },
  { title: "The Shining", description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.", poster: "https://image.tmdb.org/t/p/w500/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg", genre: ["Horror", "Mystery", "Drama"], year: 1980, director: "Stanley Kubrick", rating: 8.4, duration: 146, trailerUrl: "https://www.youtube.com/embed/5Cb3ik6zP2I" },
];

const seedMovies = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB-ye qosuldu");

    const admin = await User.findOne({ role: "admin" });
    if (!admin) {
      console.log("Admin tapilmadi. Evvelce seedAdmin.js isle salin.");
      process.exit(1);
    }

    await Movie.deleteMany({});
    console.log("Kohne filmler temizlendi");

    const moviesWithCreator = movies.map((movie) => ({
      ...movie,
      createdBy: admin._id,
    }));

    await Movie.insertMany(moviesWithCreator);
    console.log(`${movies.length} film ugurla elave olundu`);

    process.exit(0);
  } catch (error) {
    console.error("Xeta:", error.message);
    process.exit(1);
  }
};

seedMovies();